name: CI/CD Backend Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hubscore:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hubscore:latest
            docker stop spring-backend || true
            docker rm spring-backend || true
            docker run -d --name spring-backend -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e FLYWAY_DB_URL='${{ secrets.FLYWAY_DB_URL }}' \
              -e FLYWAY_DB_USER='${{ secrets.FLYWAY_DB_USER }}' \
              -e FLYWAY_DB_PASSWORD='${{ secrets.FLYWAY_DB_PASSWORD }}' \
              -e DB_URL='${{ secrets.DB_URL }}' \
              -e DB_USERNAME='${{ secrets.DB_USERNAME }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              ${{ secrets.DOCKERHUB_USERNAME }}/hubscore:latest

      - name: Ping the deployed API
        run: |
          echo "Waiting 30 seconds for the app to start..."
          sleep 30
          curl --fail --retry 5 --retry-delay 5 https://api.squash.leogouchon.com/api/ping
